-- Add ai_comment column to import_draft_rows
ALTER TABLE import_draft_rows ADD COLUMN ai_comment text;
comment on column import_draft_rows.ai_comment is 'Optional feedback or warning generated by the AI model during OCR extraction.';
